// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-observation-api/service"
	"net/http"
	"sync"
)

var (
	lockIHealthCheckMockAddCheck sync.RWMutex
	lockIHealthCheckMockHandler  sync.RWMutex
	lockIHealthCheckMockStart    sync.RWMutex
	lockIHealthCheckMockStop     sync.RWMutex
)

// Ensure, that IHealthCheckMock does implement service.IHealthCheck.
// If this is not the case, regenerate this file with moq.
var _ service.IHealthCheck = &IHealthCheckMock{}

// IHealthCheckMock is a mock implementation of service.IHealthCheck.
//
//     func TestSomethingThatUsesIHealthCheck(t *testing.T) {
//
//         // make and configure a mocked service.IHealthCheck
//         mockedIHealthCheck := &IHealthCheckMock{
//             AddCheckFunc: func(name string, checker healthcheck.Checker) error {
// 	               panic("mock out the AddCheck method")
//             },
//             HandlerFunc: func(w http.ResponseWriter, req *http.Request)  {
// 	               panic("mock out the Handler method")
//             },
//             StartFunc: func(ctx context.Context)  {
// 	               panic("mock out the Start method")
//             },
//             StopFunc: func()  {
// 	               panic("mock out the Stop method")
//             },
//         }
//
//         // use mockedIHealthCheck in code that requires service.IHealthCheck
//         // and then make assertions.
//
//     }
type IHealthCheckMock struct {
	// AddCheckFunc mocks the AddCheck method.
	AddCheckFunc func(name string, checker healthcheck.Checker) error

	// HandlerFunc mocks the Handler method.
	HandlerFunc func(w http.ResponseWriter, req *http.Request)

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context)

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// AddCheck holds details about calls to the AddCheck method.
		AddCheck []struct {
			// Name is the name argument value.
			Name string
			// Checker is the checker argument value.
			Checker healthcheck.Checker
		}
		// Handler holds details about calls to the Handler method.
		Handler []struct {
			// W is the w argument value.
			W http.ResponseWriter
			// Req is the req argument value.
			Req *http.Request
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
}

// AddCheck calls AddCheckFunc.
func (mock *IHealthCheckMock) AddCheck(name string, checker healthcheck.Checker) error {
	if mock.AddCheckFunc == nil {
		panic("IHealthCheckMock.AddCheckFunc: method is nil but IHealthCheck.AddCheck was just called")
	}
	callInfo := struct {
		Name    string
		Checker healthcheck.Checker
	}{
		Name:    name,
		Checker: checker,
	}
	lockIHealthCheckMockAddCheck.Lock()
	mock.calls.AddCheck = append(mock.calls.AddCheck, callInfo)
	lockIHealthCheckMockAddCheck.Unlock()
	return mock.AddCheckFunc(name, checker)
}

// AddCheckCalls gets all the calls that were made to AddCheck.
// Check the length with:
//     len(mockedIHealthCheck.AddCheckCalls())
func (mock *IHealthCheckMock) AddCheckCalls() []struct {
	Name    string
	Checker healthcheck.Checker
} {
	var calls []struct {
		Name    string
		Checker healthcheck.Checker
	}
	lockIHealthCheckMockAddCheck.RLock()
	calls = mock.calls.AddCheck
	lockIHealthCheckMockAddCheck.RUnlock()
	return calls
}

// Handler calls HandlerFunc.
func (mock *IHealthCheckMock) Handler(w http.ResponseWriter, req *http.Request) {
	if mock.HandlerFunc == nil {
		panic("IHealthCheckMock.HandlerFunc: method is nil but IHealthCheck.Handler was just called")
	}
	callInfo := struct {
		W   http.ResponseWriter
		Req *http.Request
	}{
		W:   w,
		Req: req,
	}
	lockIHealthCheckMockHandler.Lock()
	mock.calls.Handler = append(mock.calls.Handler, callInfo)
	lockIHealthCheckMockHandler.Unlock()
	mock.HandlerFunc(w, req)
}

// HandlerCalls gets all the calls that were made to Handler.
// Check the length with:
//     len(mockedIHealthCheck.HandlerCalls())
func (mock *IHealthCheckMock) HandlerCalls() []struct {
	W   http.ResponseWriter
	Req *http.Request
} {
	var calls []struct {
		W   http.ResponseWriter
		Req *http.Request
	}
	lockIHealthCheckMockHandler.RLock()
	calls = mock.calls.Handler
	lockIHealthCheckMockHandler.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *IHealthCheckMock) Start(ctx context.Context) {
	if mock.StartFunc == nil {
		panic("IHealthCheckMock.StartFunc: method is nil but IHealthCheck.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockIHealthCheckMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockIHealthCheckMockStart.Unlock()
	mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedIHealthCheck.StartCalls())
func (mock *IHealthCheckMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockIHealthCheckMockStart.RLock()
	calls = mock.calls.Start
	lockIHealthCheckMockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *IHealthCheckMock) Stop() {
	if mock.StopFunc == nil {
		panic("IHealthCheckMock.StopFunc: method is nil but IHealthCheck.Stop was just called")
	}
	callInfo := struct {
	}{}
	lockIHealthCheckMockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	lockIHealthCheckMockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//     len(mockedIHealthCheck.StopCalls())
func (mock *IHealthCheckMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	lockIHealthCheckMockStop.RLock()
	calls = mock.calls.Stop
	lockIHealthCheckMockStop.RUnlock()
	return calls
}
