// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-observation-api/service"
	"sync"
)

// Ensure, that IServerMock does implement service.IServer.
// If this is not the case, regenerate this file with moq.
var _ service.IServer = &IServerMock{}

// IServerMock is a mock implementation of service.IServer.
//
//     func TestSomethingThatUsesIServer(t *testing.T) {
//
//         // make and configure a mocked service.IServer
//         mockedIServer := &IServerMock{
//             ListenAndServeFunc: func() error {
// 	               panic("mock out the ListenAndServe method")
//             },
//             ShutdownFunc: func(ctx context.Context) error {
// 	               panic("mock out the Shutdown method")
//             },
//         }
//
//         // use mockedIServer in code that requires service.IServer
//         // and then make assertions.
//
//     }
type IServerMock struct {
	// ListenAndServeFunc mocks the ListenAndServe method.
	ListenAndServeFunc func() error

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// ListenAndServe holds details about calls to the ListenAndServe method.
		ListenAndServe []struct {
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockListenAndServe sync.RWMutex
	lockShutdown       sync.RWMutex
}

// ListenAndServe calls ListenAndServeFunc.
func (mock *IServerMock) ListenAndServe() error {
	if mock.ListenAndServeFunc == nil {
		panic("IServerMock.ListenAndServeFunc: method is nil but IServer.ListenAndServe was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListenAndServe.Lock()
	mock.calls.ListenAndServe = append(mock.calls.ListenAndServe, callInfo)
	mock.lockListenAndServe.Unlock()
	return mock.ListenAndServeFunc()
}

// ListenAndServeCalls gets all the calls that were made to ListenAndServe.
// Check the length with:
//     len(mockedIServer.ListenAndServeCalls())
func (mock *IServerMock) ListenAndServeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListenAndServe.RLock()
	calls = mock.calls.ListenAndServe
	mock.lockListenAndServe.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *IServerMock) Shutdown(ctx context.Context) error {
	if mock.ShutdownFunc == nil {
		panic("IServerMock.ShutdownFunc: method is nil but IServer.Shutdown was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc(ctx)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//     len(mockedIServer.ShutdownCalls())
func (mock *IServerMock) ShutdownCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}
