---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 

inputs:
  - name: dp-observation-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-observation-api/ci/scripts/build.sh
